-- Buat tabel untuk menyimpan lokasi parkir
CREATE TABLE IF NOT EXISTS public.parking_locations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  lat DOUBLE PRECISION NOT NULL,
  lng DOUBLE PRECISION NOT NULL,
  status TEXT DEFAULT 'available', -- 'available', 'almost-full', 'full'
  available_slots INTEGER NOT NULL DEFAULT 0,
  total_slots INTEGER NOT NULL DEFAULT 0,
  type TEXT NOT NULL,
  rate TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Buat tabel untuk menyimpan riwayat reservasi
CREATE TABLE IF NOT EXISTS public.reservations (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  parking_id BIGINT REFERENCES public.parking_locations(id) ON DELETE CASCADE,
  user_name TEXT NOT NULL,
  license_plate TEXT NOT NULL,
  status TEXT DEFAULT 'active', -- 'active', 'completed', 'cancelled'
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Mengaktifkan RLS (Row Level Security) agar aman, tapi untuk pengembangan kita izinkan akses publik sementara
ALTER TABLE public.parking_locations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reservations ENABLE ROW LEVEL SECURITY;

-- Buat policy (aturan) agar publik bisa membaca dan mengubah data
CREATE POLICY "Enable read access for all users" ON public.parking_locations FOR SELECT USING (true);
CREATE POLICY "Enable update access for all users" ON public.parking_locations FOR UPDATE USING (true);

CREATE POLICY "Enable read access for all users" ON public.reservations FOR SELECT USING (true);
CREATE POLICY "Enable insert access for all users" ON public.reservations FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable update access for all users" ON public.reservations FOR UPDATE USING (true);

-- Masukkan data awal (dummy data) ke tabel parking_locations
INSERT INTO public.parking_locations (name, lat, lng, status, available_slots, total_slots, type, rate)
VALUES
  ('Mall Central Parkir', -6.200000, 106.816666, 'available', 45, 100, 'Mall', 'Rp 5.000/jam'),
  ('Gedung Perkantoran Sudirman', -6.210000, 106.820000, 'full', 0, 200, 'Gedung', 'Rp 10.000/jam'),
  ('Parkir Umum Stasiun', -6.195000, 106.825000, 'almost-full', 5, 50, 'Umum', 'Rp 3.000/jam');
